name: visiomode
channels:
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pygame
  - codecov
  - pytest
  - pylint
  - pip=20.0.2
  - pip:
    - coverage==5.1
    - cython==0.29.16
    - docutils==0.16
    - flask==1.1.2
    - flask-socketio==4.2.1
    - gevent==1.5.0
    - greenlet==0.4.15
    - python-socketio==4.5.1
    - pyyaml==5.3.1
    - redis==3.4.1
    - regex==2020.4.4
    - requests==2.23.0
    - snowballstemmer==2.0.0
    - sphinx==3.0.1
