name: "Check code format"

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    name: "lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          src: "./src"
          # use_pyproject: true