name: "Check code format"

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    name: "ruff"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./src"
  typing:
    name: "mypy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install hatch
        run: |
          python -m pip install hatch

      - name: Run mypy with hatch command
        run: |
          hatch run lint:typing